server:
  port: 8090

spring.elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

logging:
  level:
    root: info
    poc: debug
    org.mongodb.driver.protocol: DEBUG
    org.springframework.data.mongodb: DEBUG

springdoc:
  packagesToScan: poc.elasticsearch.adapter.rest
  show-actuator: true
